[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor = "4W5V4Zvt6Mk1Y2L2ZGho5Y3Kmir6AyFSCaQq7xPDYaC5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/frank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
