[toolchain]

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[programs.devnet]
pixelana = "3pWVQatHK7c1f2ohgeW9baJuSh7JccmWgHSpkLVym973"

[provider]
cluster = "devnet"
wallet = "/Users/frank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
